# Generated by Django 4.0.1 on 2022-01-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productreview_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
