# Generated by Django 4.0.1 on 2022-01-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productreview_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
